language: python
python:
  - 2.7
sudo: false
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install python-coveralls
  - pip install pycurl
  - pip install urlgrabber
  - pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage --cover-package=osclib --cover-inclusive
after_success:
  - coveralls
